# set server port
server:
  port: 8888  # 配置端口
  context-path: / # 项目启动地址为 localhost:8888/

spring:
  datasource:
    #serverTimezone=GMT%2B8解决时区问题
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  aop:
    proxy-target-class: true

# thymeleaf设置
  thymeleaf:
    cache: false
    encoding: UTF-8
    # 设置LEGACYHTML5 并添加依赖 可以使thymeleaf不严格模式
    mode: LEGACYHTML5

#  mvc:
#    view: # 默认前后缀
#      prefix: /
#      suffix: .html
#    static-path-pattern: /**
#logging: #相对位置，根目录
#  path: var/log
# 日志级别 TRACE < DEBUG < INFO < WARN < ERROR < FATAL
#logging: # 配置日志文件的配置方式  logback-spring.* 也为spring的默认命名规则
#  config: logback-spring.xml




